config/routes.rb
Rails.application.routes.draw do
    resources :props
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get '/register', to: 'user#new'
    post '/register', to: 'user#create'
    get '/users/:username', to: 'user#show', as: 'profile'
    post '/users/:username', to: 'user#update'

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    get    '/logout',  to: 'sessions#destroy'
    get    '/about',   to: 'application#about'
    get    '/policy',  to: 'application#policy'  

    root to: 'application#index'
    match '*a', :to => 'errors#routing', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prop.rb
class Prop < ApplicationRecord

  validates_presence_of :image
  has_attached_file :image, styles: { large:"600x600>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # A prop is an object.
  # This makes sure that an object has a valid user, or it wont exist.
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://s16.postimg.org/y9e9y20yt/profile.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # If a user gets destroyed, delete all props owned by them.
  has_many :props, dependent: :destroy

  validates_presence_of :username, presence: true
  validates_presence_of :password_confirmation, presence: true
  validates_presence_of :password_hash, presence: true
  validates_presence_of :email, presence: true
  validates_presence_of :full_name, presence: true
  validates_uniqueness_of :username
  # Username is 3 to 40 characters with letters numbers and underscores, but cannot start or end with one.
  validates_format_of :username, with: /\A[a-zA-Z0-9][a-zA-Z0-9_]{1,38}[a-zA-Z0-9]\z/
  validates_confirmation_of :password

  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # To allow login checking on any function.
  include SessionsHelper

  def index
      if params[:search].nil?
        @searchResults = Prop.all()
      else
        @searchResults = Prop.joins(:user).where('name LIKE ? OR props.description LIKE ? OR username LIKE ? OR full_name LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%","%#{params[:search]}%")
      end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def routing
   render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => true
  end
end

app/controllers/props_controller.rb
class PropsController < ApplicationController
  before_action :set_prop, only: [:show, :edit, :update, :destroy]
  # Mostly filler content autogenerated by scaffold.

  # GET /props
  # GET /props.json
  def index
    @props = Prop.all
  end

  # GET /props/1
  # GET /props/1.json
  def show
  end

  # GET /props/new
  def new
    @prop = Prop.new
  end

  # GET /props/1/edit
  def edit
  end

  # POST /props
  # POST /props.json
  def create
    @prop = Prop.new(prop_params)
    @prop.user = current_user

    respond_to do |format|
      if @prop.save
        format.html { redirect_to @prop, notice: 'Prop was successfully created.' }
        format.json { render :show, status: :created, location: @prop }
      else
        format.html { render :new }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /props/1
  # PATCH/PUT /props/1.json
  def update
    respond_to do |format|
      if @prop.update(prop_params)
        format.html { redirect_to @prop, notice: 'Prop was successfully updated.' }
        format.json { render :show, status: :ok, location: @prop }
      else
        format.html { render :edit }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /props/1
  # DELETE /props/1.json
  def destroy
    @prop.destroy
    respond_to do |format|
      format.html { redirect_to props_url, notice: 'Prop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prop
      @prop = Prop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prop_params
      params.require(:prop).permit(:name, :description, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # Login controller.

  include ApplicationHelper

  # Login page
  def new
  end

  # Actually logs the user in.
  def create
    session_params = params[:session]
    user = User.find_by_username(session_params[:username])
    if user and user.password == session_params[:password]
      log_in user
      redirect_to '/users/' + user.username
    else
      addToErrors(:loginErrors,"Invalid Username and Password combination.")
      redirect_to :back
    end
  end

  # When this is called, log out the user.
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :set_user, only: [:show, :update]
    include ApplicationHelper

    # User profile.
    # TODO get list of props owned by user ready.
    def show
        if @user.nil?
            render 'no_user'
        end
        @userResults = Prop.where(user_id: @user)
    end

    # Register page
    def new
        @user = User.new
    end

    # Register post that will actually create the user.
    # TODO actualy send email.
    # TODO make intermidiary step for user to not be active until email.
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to :back, notice: 'Account was created.'
        else
            if @user.errors.full_messages.any?
                @user.errors.full_messages.each do |error_message|
                    addToErrors(:registerError, error_message)
                end
            end
            redirect_to :back
        end
    end

    def update
        @user.attributes = user_update_params
        @user.avatar = params.fetch(:user, {}).fetch(:avatar, @user.avatar)# THIS IS A VERY BAD FIX.  TODO SOMETHING ELSE.
        if @user.save
            redirect_to profile_path, username: @user.username, notice: 'Your user successfully updated.'
        else
            if @user.errors.full_messages.any?
                @user.errors.full_messages.each do |error_message|
                    addToErrors(:editError, error_message)
                end
            end
            redirect_to profile_path, username: @user.username, notice: 'Something went wrong, your user was not updated.'
        end
    end

    private

    def set_user
        @user = User.find_by_username(params[:username])
    end

    def user_params
        params.permit(:username, :full_name, :email, :password, :password_confirmation, :description, :avatar)
    end

    def user_update_params
        params.permit(:password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def addToErrors(where, what)
    ErrorsSetup(where)

    session[:errors][where.to_s].push(what)
  end

  def hasErrors(where)
    return session.fetch(:errors, {}).fetch(where.to_s, {}).any?
  end

  def getErrors(where)
    ErrorsSetup(where)

    toReturn = session[:errors][where.to_s]
    session[:errors][where.to_s] = []
    return toReturn
  end

  def ErrorsSetup(where)
    #Error prevention
    session[:errors] = {} if not session[:errors]
    session[:errors][where.to_s] = [] if session[:errors][where.to_s].nil?
  end

end

app/helpers/props_helper.rb
module PropsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  # Nil if not logged in.
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user_profile
    @current_user_path ||= profile_url username: current_user.username
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/about.html.erb
<div class="container">

    <!-- Introduction Row -->
    <div ng-controller="aboutCtrl" ng-app="proquo">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ header }}
                    <small>It's Nice to Meet You!</small>
                </h1>
                <p>{{ para }}</p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
            </div>

            <div ng-controller="aboutCtrl" class="col-lg-4 col-sm-6 text-center" ng-app="proquo" ng-repeat="author in authors">
                <div>
                    <img class="img-circle img-responsive img-center" ng-src={{author.pic}} alt="">
                    <h3>{{author.name}}
                        <small>{{author.job}}</small>
                    </h3>
                    <p>{{author.todo}}</p>
                </div>
            </div>
        </div>
    </div>
    <hr>

</div>
<style>
    .img-circle.img-responsive.img-center {
        margin-left: auto;
        margin-right: auto;
    }

</style>
<!-- /.container -->

app/views/application/index.html.erb
<!--Search bar at the top of the page-->
<form method="get" action=".">
<div class="input-group input-group-lg" id="search-bar">
    <span class="input-group-addon" id="sizing-addon1">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </span>
      <input type="text" class="form-control" placeholder="What are you looking for?" aria-describedby="sizing-addon1" name="search" value="<%= params[:search] %>">
</div>
</form>

<!--In the future we may use cards instead https://material.angularjs.org/latest/demo/card-->
<div ng-controller="MainCtrl as mainCtrl" ng-cloak="" class="gridListdemoBasicUsage" ng-app="proquo">

<div class='md-padding' layout="row" layout-wrap>

  <% @searchResults.each do |prop| %>
    <md-card>
      <% u = prop.user %>
      <md-card-header>
        <md-card-avatar>
          <img class="md-user-avatar" style="width:40px;height:40px;" src="<%= u.avatar.url(:thumb) %>">
        </md-card-avatar>
        <md-card-header-text>
          <span class="md-title"><%= u.username %></span>
          <span class="md-subhead"><%= u.full_name %></span>
        </md-card-header-text>
      </md-card-header>
      <img ng-src="<%= prop.image.url(:medium) %>" style="width: 200px;" class="md-card-image" alt="<%= prop.name %>">
      <md-card-title>
        <md-card-title-text>
          <span class="md-headline"><%= prop.name %></span>
          <span class="md-subhead">tags</span>
        </md-card-title-text>
      </md-card-title>
      <md-card-actions layout="row" layout-align="start center">
        <md-button>Action 1</md-button>
        <md-button>Action 2</md-button>
      </md-card-actions>
      <md-card-content>
        <p style="width: 168px;">
          <%= prop.description %>
        </p>
      </md-card-content>
    </md-card>
  <% end %>

  </div>
</div>

app/views/application/policy.html.erb
<div class="container">
    <div ng-controller="policyCtrl" ng-app="proquo">
        <h2>Privacy</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
            irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <div>
            <ol>
                <li ng-repeat="policy in policies">
                    <h4 ng-click="showDetails = ! showDetails">{{policy.name}}</h4>
                    <div class="policy_details" ng-show="showDetails">
                        <p>{{policy.content}}</p>
                </li>
            </ol>
        </div>
    </div>
</div>

app/views/props/_form.html.erb
<%= form_for(prop) do |f| %>
  <% if prop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prop.errors.count, "error") %> prohibited this prop from being saved:</h2>

      <ul>
      <% prop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <dev class="field">
    <%= f.file_field :image, class: 'form-control'%>
  </dev>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/props/edit.html.erb
<h1>Editing Prop</h1>

<%= render 'form', prop: @prop %>

<%= link_to 'Show', @prop %> |
<%= link_to 'Back', props_path %>

app/views/props/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Props</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @props.each do |prop| %>
      <tr>
        <td><%= prop.name %></td>
        <td><%= prop.description %></td>
        <td><%= prop.user.username %></td>
        <td><%= link_to 'Show', prop %></td>
        <td><%= link_to 'Edit', edit_prop_path(prop) %></td>
        <td><%= link_to 'Destroy', prop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prop', new_prop_path %>

app/views/props/new.html.erb
<h1>New Prop</h1>

<%= render 'form', prop: @prop %>

<%= link_to 'Back', props_path %>

app/views/props/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prop.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @prop.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @prop.user.username %>
</p>

<p>
  <a href="<%= @prop.image.url(:large) %>"><img alt="" src="<%= @prop.image.url(:medium) %>"></a>
</p>

<%= link_to 'Edit', edit_prop_path(@prop) %> |
<%= link_to 'Back', props_path %>

app/views/user/emailSent.html.erb
<h1>Email to be sent here</h1>

app/views/user/new.html.erb
<h1>Register</h1>

<% getErrors(:registerError).each do |error_message| %>
  <div class="alert alert-danger"><%= error_message %></div> <br />
<% end %>

<%= form_tag controller: "user", action: "create", method: "post", class: "form-group" do %>
  <%= label_tag :username %>
  <%= text_field_tag :username %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= label_tag :password_confirmation %>
  <%= password_field_tag :password_confirmation %>
  <br>
  <%= submit_tag "Register" %>
<% end %>

app/views/user/no_user.html.erb
<body np-app="proquo">
    <div id="content">
        <div id="main-body">
            <p class="enormous-font bree-font">
                Oh no...
            </p>
            <p class="big-font">
                It looks like @<%= params[:username] %> isn't here right now. You should probably come back later.
            </p>
            <p class="big-font">
                Let's just go back to the
                <a href="/" class="underline">home page</a>.
            </p>
        </div>
    </div>
</body>

app/views/user/show.html.erb
<div class="card hovercard">
    <div class="card-background">
        <img class="card-bkimg" alt="" src="<%= @user.avatar.url(:medium) %>">
    </div>
    <div class="useravatar">
        <img alt="" src="<%= @user.avatar.url(:medium) %>">
    </div>
    <div class="card-info"> <span class="card-title"><%= @user.username %></span>

    </div>
</div>

<div class='md-padding' layout="row" layout-wrap>

  <% @userResults.each do |prop| %>
    <md-card>
      <% u = prop.user %>
      <md-card-header>
        <md-card-avatar>
          <img class="md-user-avatar" style="width:40px;height:40px;" src="<%= u.avatar.url(:thumb) %>">
        </md-card-avatar>
        <md-card-header-text>
          <span class="md-title"><%= u.username %></span>
          <span class="md-subhead"><%= u.full_name %></span>
        </md-card-header-text>
      </md-card-header>
      <img ng-src="<%= prop.image.url(:medium) %>" style="width: 200px;" class="md-card-image" alt="<%= prop.name %>">
      <md-card-title>
        <md-card-title-text>
          <span class="md-headline"><%= prop.name %></span>
          <span class="md-subhead">tags</span>
        </md-card-title-text>
      </md-card-title>
      <md-card-actions layout="row" layout-align="start center">
        <md-button>Action 1</md-button>
        <md-button>Action 2</md-button>
      </md-card-actions>
      <md-card-content>
        <p style="width: 168px;">
          <%= prop.description %>
        </p>
      </md-card-content>
    </md-card>
  <% end %>

</div>